language: node_js
node_js: node

notifications:
  email: false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script: yarn build

after_script: greenkeeper-lockfile-upload

after_success: yarn semantic-release
